### ISSUE TITLE
Image auto crop is not working

### ISSUE THREAD

**Issue by mkashifsnyder** [A-l-y-l-e/Alyle-UI#121]
### Describe the bug
Image autoCrop: true is not working in the latest version. previously it was working fine.

### Minimal Reproduction
Turn on autoCrop property and then move the image it should automatically crop it. but it doesnt;

**Comment by Enlcxx** [comment]
Hi @mkashifsnyder I just checked it and yes the `autocrop` is not working properly. Thanks for reporting.
