### ISSUE TITLE
How to delete Default global styles.

### ISSUE THREAD

**Issue by mkashifsnyder** [A-l-y-l-e/Alyle-UI#122]
# :beetle: Bug report

### Describe the bug
How we can delete global styles or move them to component level, cause these are conflicting with other component's, where i doesn't used any control from alyui. 

### Screenshots

![image](https://user-images.githubusercontent.com/68124850/87220009-4524f180-c315-11ea-8d43-72413f9f0b5b.png)

### Which versions of Angular, Alyle UI, OS, TypeScript, browsers are affected?

**Alyle UI Version:** 
`3.4.0`

**Angular Version:**
10

**Comment by Enlcxx** [comment]
Are causing conflicts? Can you give me more details? What did you do to render various styles?

Styles are rendered only when the element requires it, apparently this one element is rendering many styles

**Comment by mkashifsnyder** [comment]
We are using kendo drawer component for side menu and some how these styles are overriding the styles of kendo components like kendo drawer and kendo dialog etc...

![image](https://user-images.githubusercontent.com/68124850/87233231-87344e80-c37a-11ea-8e41-1d2b9dc939b5.png)

after remove the style from chrome inspect element and it fixed that issue...
![image](https://user-images.githubusercontent.com/68124850/87233272-c498dc00-c37a-11ea-8059-ce720a006c80.png)

**Comment by mkashifsnyder** [comment]
we just added following in our controls.modules.ts

import {
  LyTheme2,
  StyleRenderer,
  LY_THEME,
  LY_THEME_NAME,
  LY_THEME_GLOBAL_VARIABLES,
  LyHammerGestureConfig
} from '@alyle/ui';
import { MinimaLight, MinimaDark } from '@alyle/ui/themes/minima';
import { BrowserModule, HAMMER_GESTURE_CONFIG, HammerModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { color } from '@alyle/ui/color';

export class GlobalVariables {
  testVal = color(0x00bcd4);
  Quepal = {
    default: `linear-gradient(135deg,#11998e 0%,#38ef7d 100%)`,
    contrast: color(0xffffff),
    shadow: color(0x11998e)
  };
  SublimeLight = {
    default: `linear-gradient(135deg,#FC5C7D 0%,#6A82FB 100%)`,
    contrast: color(0xffffff),
    shadow: color(0xB36FBC)
  };
  Amber = {
    default: color(0xffc107),
    contrast: color(0, 0, 0, 0.87)
  };
}


providers: [
    [ LyTheme2 ],
    [ StyleRenderer ],
    { provide: LY_THEME_NAME, useValue: 'minima-light' },
    {
      provide: LY_THEME,
      useClass: MinimaLight,
      multi: true
    },
    {
      provide: LY_THEME,
      useClass: MinimaDark,
      multi: true
    },
    {
      provide: LY_THEME_GLOBAL_VARIABLES,
      useClass: GlobalVariables
    }, // global variables
    // Gestures
    { provide: HAMMER_GESTURE_CONFIG, useClass: LyHammerGestureConfig }
  ],

**Comment by mkashifsnyder** [comment]
FYI our control module contains control from kendo, primeng and alyle ui.. might possible because of that we are facing this issue?

**Comment by Enlcxx** [comment]
I think there is a conflict with the attribute `[width]`. Alyle UI has a directive to style elements, [here](https://alyle.io/styles/sizing) you  can see about Sizing.

**Comment by mkashifsnyder** [comment]
i will try to move alyle -ui controls to separate module.. may be that will resolve the conflict...

**Comment by Enlcxx** [comment]
yes, I think it has conflict with Kendo

**Comment by mkashifsnyder** [comment]
it looks like alyle ui [width] and [height] directives are trying to override kendo input properties like [width] and [height]. whenever we are trying to put [width]="width" with kendo controls like kendo dialog etc, alyle ui is trying to add class like LyStyle--width-800-i. Is there anyway we can turn off alyle ui [width] and [height] directives?

**Comment by mkashifsnyder** [comment]
FYI it was working fine on version 2.9.7 even with all libraries...

**Comment by mkashifsnyder** [comment]
we have resolved that issue for now by moving alyle ui controls to a separate module.  Enlcxxx thanks for quick response and we really like image cropper of alyle ui great job...

**Comment by Enlcxx** [comment]
Thanks, you're welcome.
I'm probably going to prefix the attributes, for example, `width` to `lyWidth`, so there are no conflicts with other libraries.

**Comment by Enlcxx** [comment]
Prefixed.
