### ISSUE TITLE
Image cropper do not allows you to zoom out beyond the limit of the image

### ISSUE THREAD

**Issue by BruneXX** [A-l-y-l-e/Alyle-UI#124]
# :rocket: Feature request

### Description
I'm always frustrated when the cropper do not allows you to zoom out beyond the limit of the image when the image you uploaded is not square and fills the background

Example of the issue:
![chrome_LjE1u098aF](https://user-images.githubusercontent.com/28172522/87802560-c6a1e580-c827-11ea-8574-545d2b79db77.png)

### Describe the solution you'd like
Allows you to zoom out beyond the limit of the image when the image you uploaded is not square and fills the background

### Describe alternatives you've considered
Use another cropper component.

**Comment by BruneXX** [comment]
Just in case this is the image that I've used for the test:
![Banner ML](https://user-images.githubusercontent.com/28172522/87802974-4fb91c80-c828-11ea-97f4-21ee152223fe.jpg)

**Comment by Enlcxx** [comment]
You can use [`ImgCropperConfig.extraZoomOut`](https://alyle.io/api/@alyle/ui/image-cropper/ImgCropperConfig).
In your image cropper config:

```ts
myConfig: ImgCropperConfig = {
  ...
  extraZoomOut: true
}
```

**Comment by BruneXX** [comment]
Hi @Enlcxx great! I didn't find it in the documentation.. if is not there it will be good to be added.

**Comment by Enlcxx** [comment]
I'll add it to the documentation, thanks for reporting this.
