### ISSUE TITLE
ERROR TypeError: m.alpha is not a function

### ISSUE THREAD

**Issue by BruneXX** [A-l-y-l-e/Alyle-UI#132]
# :beetle: Bug report

### Describe the bug
Console error because a function wasn't found.

### Minimal Reproduction
Just use the image cropper and try to upload an image, and the error will arise.

### Exception or Error
<pre><code>
ERROR TypeError: (intermediate value)(intermediate value)(intermediate value).luminance is not a function
ERROR TypeError: m.alpha is not a function</code></pre>

### Which versions of Angular, Alyle UI, OS, TypeScript, browsers are affected?

** Browser:**
`Chrome 84.0.4147.105`

**Typescript:**
`v3.9.7`

**Alyle UI Version:** 
`v10.0.0`

**Angular Version: **
`v10.0.11`

![alyle_image_upload_error](https://user-images.githubusercontent.com/28172522/90918211-a4692d80-e3ba-11ea-9de7-4a80e652a546.png)

**Comment by BruneXX** [comment]
Thanks I've managed to fixed that but I'm experiencing a new error, since I've removed the theme to use an empty one now I'm receiving an error regaring **durations** when I'm trying to use the Zoom slider:

```
  <ng-container *ngIf="ready">
    <ly-slider
      [thumbVisible]="false"
      [min]="minScale"
      [max]="1"
      [(ngModel)]="scale"
      (input)="scale = $event.value"
      step="0.000001"></ly-slider>
  </ng-container>
```

After select the image this error arise:
`ERROR TypeError: Cannot read property 'durations' of undefined`

And after navigate to the error, the problematic file is **alyle-ui.slider.ts** on line 106

`${theme.animations.durations.entering}ms`

**Comment by BruneXX** [comment]
Did you know how can totally bypass the theme?

**Comment by Enlcxx** [comment]
It's not possible. Why do you want to remove the theme? most of the components depend on it.

**Comment by BruneXX** [comment]
Hi @Enlcxx I saw in another issue that it's possible #106
Like @saleh313k I'm only using image-cropper and nothing else.. Also I'm using material and I don't want to to have an extra theme that I'll not use. That's the main reason.

**Comment by BruneXX** [comment]
I've reviewed this, and the issue is reproducible also in the slackblitz demo of the issue #106 making some changes:
![durations_issue](https://user-images.githubusercontent.com/28172522/91459640-3c549480-e85d-11ea-9d2d-de717b406ee0.png)

**Comment by Enlcxx** [comment]
I see you are using `<ly-slider>`, that component requires some variables from a theme, so you have to add the missing variables.

**Comment by Enlcxx** [comment]
For it to work you have to use another slider, since `<ly-slider>` depends on some theme variables.

**Comment by BruneXX** [comment]
Excellent, I think I can use material slider, perfect! thanks for your help :)
