### ISSUE TITLE
Suggestion: Contribution guidelines

### ISSUE THREAD

**Issue by wassimoo** [A-l-y-l-e/Alyle-UI#136]
# :rocket: Feature request

Is this project open for contributions (especially for new features)? If so, I'd suggest you provide us with the contributions guidelines.

Thank you!

**Comment by Enlcxx** [comment]
Of course, any contribution is welcome, but for a **Major Feature** it should be discussed.

In a few days I'll add the Contribution guidelines

**Comment by Enlcxx** [comment]
Added contribution guidelines.
https://github.com/A-l-y-l-e/Alyle-UI/blob/master/CONTRIBUTING.md
