### ISSUE TITLE
Image cropper doesn't save correct rotation when cropped

### ISSUE THREAD

**Issue by gtan14** [A-l-y-l-e/Alyle-UI#138]
# :beetle: Bug report

### Describe the bug
When using image cropper, rotating the image -90 degrees more than once saves as just -90 in the rotation when cropped.

### Minimal Reproduction
1) Implement Image Cropper code
2) Rotate image twice
3) Crop
4) View `ImgCropperEvent` in `onCropped` event
5) Shows as -90 / 90 even when rotated multiple times

### Which versions of Angular, Alyle UI, OS, TypeScript, browsers are affected?

**Alyle UI Version:** 
10.3.0

**Angular Version:**
9.1.0

**Comment by Enlcxx** [comment]
Yes, it is a bug, it should show the degrees the image was rotated and not the last rotation performed.
There are also problems with the `type`, `scale`, `size` & `name`. Those properties are not available when cropping.
Related: #102

**Comment by gtan14** [comment]
Thanks for fixing!
