### ISSUE TITLE
bug(slider): error when using a disabled ly-slider

### ISSUE THREAD

**Issue by janhocevar** [A-l-y-l-e/Alyle-UI#145]
# :beetle: Bug report

### Describe the bug
I'm using the image cropper in combination with the slider, pretty much identical implementation that described here - https://stackblitz.com/angular/xaagvxdgbvpr?file=app%2Fcrop-circle.component.html

### Reproduction
```typescript
const STYLES = (_theme: ThemeVariables, ref: ThemeRef) => {
  ref.renderStyleSheet(CROPPER_STYLES);
  const cropper = ref.selectorsOf(CROPPER_STYLES);
  const slider = ref.selectorsOf(SLIDER_STYLES);

  return {
    root: lyl `{
      ${cropper.root} {
        width: 260px
        height: 180px,
      }
    }`,
    sliderContainer: lyl `{
      text-align: center
      width: 100%

      ${slider.track} {
        background: linear-gradient(${
          [
            '180deg',
            '#7A59DB 0%',
            '#583AB0 100%'
          ].join()
        })
      }

      ${slider.thumb} {
        width: 14px
        height: 14px
        top: -7px
      }
    }`,
  };
};
```

```typescript
export class AvatarUploaderComponent implements AfterViewInit, OnDestroy {
  @ViewChild('avatarImageFileUploader') avatarImageFileUploader: ElementRef;
  @ViewChild(LyImageCropper, { static: true }) readonly cropper: LyImageCropper;

  croppedImage: Blob;
  error: string | null;
  showCropper: boolean;

  imageMaxFileSize = 1760735;
  readonly classes = this.sRenderer.renderSheet(STYLES, 'root');
  scale: number;
  ready: boolean;
  minScale: number;
  myConfig: ImgCropperConfig = {
    width: 150, // Default `250`
    height: 150, // Default `200`
    type: 'image/png,image/jpeg,image/gif',
    round: true,
    maxFileSize: this.imageMaxFileSize
  };

  constructor(
    private readonly sRenderer: StyleRenderer,
  ) { }

  ngAfterViewInit() {
    this.avatarImageFileUploader.nativeElement.click();
  }
```

```html
<div class="avatar-uploader">
  <input type="file" (change)="cropper.selectInputEvent($event)" #avatarImageFileUploader class="avatar-uploader__file-input" accept="image/png,image/jpeg,image/gif" />

  <div class="avatar-uploader__image-cropper-wrapper" [class.avatar-uploader__image-cropper-wrapper--empty]="!ready">
    <ly-img-cropper
      [config]="myConfig"
      [(scale)]="scale"
      (minScale)="minScale = $event"
      (ready)="ready = true"
      (cleaned)="ready = false"
      (cropped)="onCropped($event)"
      (loaded)="onLoaded($event)"
      (error)="onError($event)">
    </ly-img-cropper>
  </div>

  <div class="cropper-error" *ngIf="error">{{error | translate}}</div>

  <div class="zoom-controls">
    <div class="zoom-control" (click)="cropper.zoomOut()"><img src="/assets/icons/zoom-out.svg"></div>
    <div [className]="classes.sliderContainer">
      <ly-slider
        [thumbVisible]="false"
        [min]="minScale"
        [max]="1"
        [(ngModel)]="scale"
        (input)="scale = $event.value"
        [disabled]="isSliderDisabled"
        step="0.000001"></ly-slider>
    </div>
    <div class="zoom-control" (click)="cropper.zoomIn()"><img src="/assets/icons/zoom-in.svg"></div>
  </div>

  <div class="footer-buttons">
    <button mat-button color="primary" (click)="saveImage()" [disabled]="isActionDisabled" *ngIf="croppedImage">{{'COMMON.SAVE' | translate}}</button>
    <button mat-button color="primary" (click)="cropper.crop()" [disabled]="!ready" *ngIf="!croppedImage">{{'COMMON.CROP' | translate}}</button>
    <div class="button--cancel" (click)="closeModal()">{{'COMMON.CANCEL' | translate}}</div>
  </div>
</div>
```

```typescript
/** Import Alyle UI */
import {
  LyTheme2,
  StyleRenderer,
  LY_THEME,
  LY_THEME_NAME,
  LyHammerGestureConfig,
} from '@alyle/ui';

import { MinimaLight } from '@alyle/ui/themes/minima';

import { AvatarUploaderComponent } from './avatar-uploader.component';
import { FormsModule } from '@angular/forms';
@NgModule({
  imports: [
    CommonModule,
    TranslateModule,
    MatButtonModule,
    DragDropModule,
    LyImageCropperModule,
    LySliderModule,
    HammerModule,
    FormsModule,
  ],
  declarations: [
    AvatarUploaderComponent
  ],
  exports: [
    AvatarUploaderComponent
  ],
  providers: [
    [ LyTheme2 ],
    [ StyleRenderer ],
    // Theme that will be applied to this module
    { provide: LY_THEME_NAME, useValue: 'minima-light' },
    { provide: LY_THEME, useClass: MinimaLight, multi: true }, // name: `minima-light`
    // Gestures
    { provide: HAMMER_GESTURE_CONFIG, useClass: LyHammerGestureConfig }
  ]
```

This happens once `ngAfterViewInit` is called (file prop is initiated on component render)

### Exception or Error
<pre><code>
app-error-handler.service.ts:49 TypeError: Cannot read property '0' of undefined
    at MinimaLight.colorOf (alyle-ui.js:508)
    at newStyle (alyle-ui-slider.js:348)
    at LyTheme2._createStyleContent2 (alyle-ui.js:1407)
    at StyleRenderer.add (alyle-ui.js:2475)
    at LySlider.set disabled [as disabled] (alyle-ui-slider.js:360)
    at Object.ngOnChangesSetInput [as setInput] (core.js:1509)
    at setInputsForProperty (core.js:10878)
    at elementPropertyInternal (core.js:9925)
    at ɵɵproperty (core.js:14655)
    at AvatarUploaderComponent_Template (avatar-uploader.component.html:23)
</code></pre>

### Which versions of Angular, Alyle UI, OS, TypeScript, browsers are affected?

**Alyle UI Version:** 
`v10.5.1`

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 11.2.4
Node: 12.20.0
OS: darwin x64

Angular: 12.0.0-next.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1102.4
@angular-devkit/build-angular      0.1102.4
@angular-devkit/core               11.2.4
@angular-devkit/schematics         11.2.4
@angular/cdk                       11.2.4
@angular/cli                       11.2.4
@angular/material                  11.2.4
@angular/material-moment-adapter   11.2.4
@nguniversal/express-engine        9.1.1
@schematics/angular                8.3.29
@schematics/update                 0.1102.4
rxjs                               6.5.5
typescript                         4.0.7

</code></pre>

Also tried with Angular v10 and v11.

**Comment by Enlcxx** [comment]
I see, this happens when using a `ly-slider` with `[disabled]="true"`, it is a bug:
```html
<ly-slider
    [min]="1"
    [max]="10"
    [disabled]="true" <-- Here
></ly-slider>
```
This will be fixed in the new version, meanwhile you can do this:
```html
<ly-slider
    [min]="1"
    [max]="10"
    [color]="'primary'" <-- Add this
    [disabled]="true"
></ly-slider>
```
Thanks for reporting this.

**Comment by janhocevar** [comment]
Thanks, it worked!
