### ISSUE TITLE
Alyle UI Image cropping plugin dosen't support latest version of Chrome

### ISSUE THREAD

**Issue by ashliman** [A-l-y-l-e/Alyle-UI#162]
Alyle UI Image cropping plugin doesn't support latest version of Chrome. After cropping it display black image.

Version 93.0.4577.63 (Official Build) (64-bit)

Please do needful

**Comment by Enlcxx** [comment]
Seems to be that it is not working well in the dialog box.

**Comment by ashliman** [comment]
Previously it was working very well in dialog also, I'm using **"@alyle/ui": "^8.1.0"**, version in Angular 8.

**Comment by Enlcxx** [comment]
Fixed
