### ISSUE TITLE
Alyle version that supports Angular 16

### ISSUE THREAD

**Issue by VinayKumarSarda** [A-l-y-l-e/Alyle-UI#223]
Can you please provide which version of Alyle supports Angular 16

**Comment by Enlcxx** [comment]
There is still no support for version 16 of Angular. I'll be working on it this week.

**Comment by sholomellenbogen** [comment]
Hey, any updates on this?

**Comment by Enlcxx** [comment]
New version released. 
https://www.npmjs.com/package/@alyle/ui/v/16.0.0
