### ISSUE TITLE
Image cropper

### ISSUE THREAD

**Issue by MrBananaGuard** [A-l-y-l-e/Alyle-UI#6]
Your example image cropper doesn't work... the viewchild object is undefined

**Comment by venuevoke** [comment]
its not working for me as well

**Comment by MrBananaGuard** [comment]
Just used Croppie. Its super easy to implement and works really well.

**Comment by developersamim** [comment]
It's not working for me as well. Viewchild object undefined

**Comment by alyleui** [comment]
Please can provide a reproduction in StackBlitz
[Here](https://alyle-ui.firebaseapp.com/components/resizing-cropping-images) some examples working
