### ISSUE TITLE
Error: LY_THEME undefined

### ISSUE THREAD

**Issue by josnar** [A-l-y-l-e/Alyle-UI#67]
#### What are the steps to reproduce?

Provide a reproduction in StackBlitz

StackBlitz starter: https://stackblitz.com/edit/angular-alyle-ui-starter

#### Which versions of Angular, AlyleUI, OS, TypeScript, browsers are affected?

Version of `@alyle/ui@`: 

```sh
$ node_modules/.bin/ng --version
Angular CLI: ...
Node: ...
OS: ...
Angular: ...
...
...
...

```

**Comment by Enlcxx** [comment]
Hi
In app.module.ts add this

```ts
import {
  LyThemeModule,
  LY_THEME
} from '@alyle/ui';
```
Follow the steps that are [here](https://alyle-ui.firebaseapp.com/getting-started/installation)

**Comment by josnar** [comment]
> Hi
> In app.module.ts add this
> 
> ```ts
> import {
>   LyThemeModule,
>   LY_THEME
> } from '@alyle/ui';
> ```
> 
> Follow the steps that are [here](https://alyle-ui.firebaseapp.com/getting-started/installation)

i added but still not working,would it support for angular 6

**Comment by Enlcxx** [comment]
Alyle UI has support for 
Angular ^6.1.10 - 7.x.x
Typescript ^2.9.2

```
Angular CLI: 6.2.8
Node: 10.9.0
OS: linux x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.8
@angular-devkit/build-angular     0.8.8
@angular-devkit/build-optimizer   0.8.8
@angular-devkit/build-webpack     0.8.8
@angular-devkit/core              0.8.8
@angular-devkit/schematics        0.8.8
@angular/cli                      6.2.8
@ngtools/webpack                  6.2.8
@schematics/angular               0.8.8
@schematics/update                0.8.8
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.16.4
```

**Comment by Enlcxx** [comment]
What versions of Angular, Alyle UI and TypeScript are you using? Can you provide a reproduction in StackBlitz

**Comment by haovc** [comment]
You just need add in core module(app.module.ts):
providers: [
    {
      provide: LY_THEME,
      useClass: MinimaLight
    },
    {
      provide: LY_THEME_GLOBAL_VARIABLES,
      useClass: GlobalVariables
    } // global variables
  ]

**Comment by Enlcxx** [comment]
The themes must be added in the root module of the application, not in sub modules.
