### ISSUE TITLE
Image moving out of range when cropper frame  aspect ratio not a square

### ISSUE THREAD

**Issue by VaruzhGhazaryan** [A-l-y-l-e/Alyle-UI#68]
### Screenshots

![sketch 1](https://user-images.githubusercontent.com/20204921/50225950-5f0d8500-03bb-11e9-912b-331d33d9d479.png)

**Alyle UI Version:** 
`v1.9.8`

**Angular Version:**
`7.1.3`

**Comment by Enlcxx** [comment]
Hi
Fixed in the next version

**Comment by VaruzhGhazaryan** [comment]
Lot of thanks
