### ISSUE TITLE
min scale not updated after rotating image

### ISSUE THREAD

**Issue by VaruzhGhazaryan** [A-l-y-l-e/Alyle-UI#69]
### Screenshots
![sketch 1](https://user-images.githubusercontent.com/20204921/50291456-1243b000-0488-11e9-993d-cf442961d062.png)

**Comment by Enlcxx** [comment]
Fixed in next version

**Comment by VaruzhGhazaryan** [comment]
Thanks for attention.

but this issue is still there

**Comment by Enlcxx** [comment]
The changes will be for version 2.0.0, is not yet release

**Comment by Enlcxx** [comment]
Fixed in 1.9.10

**Comment by VaruzhGhazaryan** [comment]
Thanks
