### ISSUE TITLE
IPAD carousel Issue

### ISSUE THREAD

**Issue by accenthomescl** [A-l-y-l-e/Alyle-UI#75]
![img_0206](https://user-images.githubusercontent.com/47165918/52163261-17d41d00-26f9-11e9-826d-b18542e9ab8e.PNG)

Please see the images from iPad/ iphone i get issues but from all ther device its working perfect.
![login](https://user-images.githubusercontent.com/47165918/52163300-9630bf00-26f9-11e9-9b27-2a5702acfa5b.png)

my component 
--------------------
const styles = {
    carousel: {
      maxWidth: '100%',
      height: '100%',
      //margin: '0PX'
    },
    carouselItem: {
      textAlign: 'center'
    }
  };

 classes = this.theme.addStyleSheet(styles);
    items: any[] = [
      {
        title: 'Grow your business with us',
        img: 'assets/images/backgrounds/bg1.jpg'
      },
      {
        title: 'Grow your business with us', 
        img: 'assets/images/backgrounds/bg2.jpg'
      }, 
      {
        title: 'Grow your business with us', 
        img: 'assets/images/backgrounds/bg3.jpg'
      }, 
      {
        title: 'Grow your business with us', 
        img: 'assets/images/backgrounds/bg4.jpg'
      },  
      {
        title: 'Grow your business with us', 
        img: 'assets/images/backgrounds/bg5.jpg'
      }, 
      {
        title: 'Grow your business with us', 
        img: 'assets/images/backgrounds/bg6.jpg'
      }, 
      {
        title: 'Grow your business with us', 
        img: 'assets/images/backgrounds/bg7.jpg'
      }, 
    ];

//////////////////////////////////// html //////

<div id="login" class="inner-scroll" fxLayout="row" fxLayoutAlign="start">

    <div id="login-intro" fxFlex fxHide fxShow.gt-xs>

        
 
        <ly-carousel [withClass]="classes.carousel">
            <ly-carousel-item [withClass]="classes.carouselItem" *ngFor="let item of items" [srcImg]="item.img">
                <div class="logo" >
                    <img src="assets/images/logos/dealsmango.svg">
                </div>
                <div class="title" >
                    {{item.title}}
                </div> 
            </ly-carousel-item>
        </ly-carousel>
    </div>

    <div id="login-form-wrapper" fusePerfectScrollbar >

        <div id="login-form">

            <div class="logo" fxHide.gt-xs>
                <img src="assets/images/logos/dealsmango.svg">
            </div>

            <div class="title">Login to your account</div>

            <form name="loginForm" [formGroup]="loginForm" novalidate>

                <mat-form-field appearance="outline">
                    <mat-label>Email</mat-label>
                    <input matInput placeholder="Email" formControlName="email">
                    <mat-error *ngIf="loginForm.get('email').hasError('required')">
                        Email is required
                    </mat-error>                   
                    <mat-error
                        *ngIf="!loginForm.get('email').hasError('required') &&
                                loginForm.get('email').hasError('email')">
                        Please enter a valid email address
                    </mat-error>
                </mat-form-field>
               
                <mat-form-field appearance="outline">
                    <mat-label>Password</mat-label>
                    <input matInput type="password" formControlName="password">
                    <mat-error>
                        Password is required
                    </mat-error>
                </mat-form-field>

                <div class="remember-forgot-password" fxLayout="row" fxLayout.xs="column"
                    fxLayoutAlign="space-between center">
                </div>
                
                <button mat-raised-button color="accent" (click)="login()" class="submit-button" aria-label="LOGIN"
                        [disabled]="loginForm.invalid">
                    LOGIN
                </button>

                <div class="register" fxLayout="column" fxLayoutAlign="center center">
                    <span class="text">Don't have an account?</span>
                    <a class="link" [routerLink]="'/register'">Create an account</a>
                </div>
            </form>

        </div>

    </div>

</div>

/////////////////////// scss//////////////////

login-2 {

    #login {
        width: 100%;
        overflow: hidden;
       
        background-size: cover;
        height: 100vh;

        #login-intro {
            padding: 0px;
            max-width: 70%;
            @include media-breakpoint('sm') {
                padding: 0px 0px;
            }

            .logo {
                width: 128px;
                margin-bottom: 32px;
            }

            .title {
                font-size: 42px;
                font-weight: 300;
                line-height: 1;
            }

            .description {
                padding-top: 16px;
                font-size: 14px;
                max-width: 600px;
            }
        }

        #login-form-wrapper {
            width: 400px;
            //min-width: 400px;
            //max-width: 400px;
            
            min-width: 30%;
            max-width: 30%;
            overflow: auto;
            -webkit-overflow-scrolling: touch;

            @include mat-elevation(16);

            @include media-breakpoint('sm') {
                width: 30%;
                min-width: 30%;
                max-width: 30%;
            }

            @include media-breakpoint('xs') {
                width: 100%;
                min-width: 100%;
                max-width: 100%;
            }

            #login-form {
                padding: 128px 23px 23px 23px;

                @include media-breakpoint('xs') {
                    text-align: center;
                    padding: 10px;
                }

                .logo {
                    width: 128px;
                    margin: 32px auto;
                }

                .title {
                    font-size: 21px;
                    text-align: center;
                }

                .description {
                    padding-top: 8px;
                }

                form {
                    width: 100%;
                    padding-top: 32px;

                    mat-form-field {
                        width: 100%;

                        @include media-breakpoint('xs') {
                            width: 80%;
                        }
                    }

                    mat-checkbox {
                        margin: 0;
                    }

                    .remember-forgot-password {
                        font-size: 13px;
                        margin-top: 8px;

                        .remember-me {
                            margin-bottom: 16px
                        }

                        .forgot-password {
                            font-size: 13px;
                            font-weight: 600;
                            margin-bottom: 16px
                        }
                    }

                    .submit-button {
                        width: 100%;
                        margin: 16px auto;
                        display: block;

                        @include media-breakpoint('xs') {
                            width: 80%;
                        }
                    }
                }

                .separator {
                    font-size: 15px;
                    font-weight: 600;
                    margin: 24px auto;
                    position: relative;
                    overflow: hidden;
                    width: 100px;
                    text-align: center;

                    .text {
                        display: inline-flex;
                        position: relative;
                        padding: 0 8px;
                        z-index: 9999;

                        &:before,
                        &:after {
                            content: '';
                            display: block;
                            width: 30px;
                            position: absolute;
                            top: 10px;
                            border-top: 1px solid;
                        }

                        &:before {
                            right: 100%;
                        }

                        &:after {
                            left: 100%;
                        }
                    }
                }

                button {

                    &.google,
                    &.facebook {
                        width: 70%;
                        text-transform: none;
                        color: #FFFFFF;
                        font-size: 13px;

                        @include media-breakpoint('xs') {
                            width: 60%;
                        }

                        mat-icon {
                            color: #FFFFFF;
                            margin: 0 8px 0 0;
                        }
                    }

                    &.google {
                        background-color: #D73D32;
                        margin-bottom: 8px;
                    }

                    &.facebook {
                        background-color: rgb(63, 92, 154);
                    }
                }

                .register {
                    margin: 32px auto 24px auto;
                    width: 250px;
                    font-weight: 600;

                    .text {
                        margin-right: 8px;
                    }

                    .link {

                    }
                }
            }
        }
    }
}

**Comment by Enlcxx** [comment]
I think it's not a carousel problem, maybe the container has something to do with it. try adding `height: 100vh` to the carousel.

I think [this](https://stackoverflow.com/questions/7049875/why-doesnt-height-100-work-to-expand-divs-to-the-screen-height) can help you.

**Comment by accenthomescl** [comment]
Thanks it worked
