### ISSUE TITLE
delete default global styles

### ISSUE THREAD

**Issue by BobaFett58** [A-l-y-l-e/Alyle-UI#77]
# :rocket: Feature request

### Description
Hi, thx you for your awesome project, but I have a small issue with the default global styles.

### Describe the solution you'd like
I don't need this global styles in my project

![image](https://user-images.githubusercontent.com/16953976/55222831-23315980-520d-11e9-8c97-1336fbe289a9.png)

Can you pls tell me, how I can delete or configure these?

Best regards.

**Comment by Enlcxx** [comment]
Hi @BobaFett58, some components depend on that style, for now it is not possible to eliminate it or prevent its creation, for now you can create another style to override it.

```ts
...
import { LyTheme2, ThemeVariables } from '@alyle/ui';

const styles = (theme: ThemeVariables) => ({
  '@global': {
    ... // others styles
    '*, *:after, *:before': {
      '-webkit-box-sizing': 'initial',
      '-moz-box-sizing': 'initial',
      'box-sizing': 'initial'
    }
  }
});

@Component({...})
export class AppComponent {
  readonly classes = this.theme.addStyleSheet(styles);
  constructor(
    private theme: LyTheme2
  ) { }
}
```

I'm thinking about eliminating that style in a next version, since only some components use it.

**Comment by BobaFett58** [comment]
Awesome, it works for my solution. Thanks, @Enlcxx, for the quick response.

**Comment by Enlcxx** [comment]
In version [2.7.0](https://github.com/A-l-y-l-e/Alyle-UI/blob/master/CHANGELOG.md#270-2019-04-18), default global styles is removed.
