### ISSUE TITLE
More documentation for lazy loaded module implementation

### ISSUE THREAD

**Issue by fitness23** [A-l-y-l-e/Alyle-UI#78]
Please could you provide more documentation for use in lazy loaded module projects? Specifically please could you provide an example using the image resized and cropper module?

**Comment by Enlcxx** [comment]
I have added the [documentation](https://alyle-ui.firebaseapp.com/guides/lazy-loading) to the page, and here a [example](https://stackblitz.com/edit/angular-26jzgq?file=src%2Fapp%2Fapp.component.html) working.
