### ISSUE TITLE
Ly-select not working

### ISSUE THREAD

**Issue by zevet** [A-l-y-l-e/Alyle-UI#80]
# :beetle: Bug report

### Describe the bug
I'm trying to use the ly-select but it is giving me an error.
I just copied the example from docs but when clickng to select an option it gives an error.

### Exception or Error
<pre>Error: No component factory found for LyOverlayBackdrop. Did you add it to @NgModule.entryComponents?<code>

</code></pre>

### Which versions of Angular, Alyle UI, OS, TypeScript, browsers are affected?

**Alyle UI Version:** 
`2.7.6`

**Angular Version:**
<pre>7.2.0<code>

Angular CLI: 7.3.9
Node: 10.15.3
OS: linux x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Comment by Enlcxx** [comment]
Hi @zevet, I tried to reproduce the problem, but I do not get that error. You may be using a previous version of Alyle UI.

Please, I need more information.

**Comment by Enlcxx** [comment]
I tried to load the component in lazy-loading and I got the mentioned error. Did you do the same?

**Comment by zevet** [comment]
Yes. I have the App component and another component being loade with lazy-loading. This lazy-laoaded component uses the Select Component

**Comment by Enlcxx** [comment]
I think this error is also shown for all components that depend on `LyOverlayModule` with lazy-loading. For now you can do is add `LyOverlayModule` in your `AppModule`.

```ts
...
import { LyOverlayModule } from '@alyle/ui';

@NgModule({
  ...
  imports: [
    ...
    LyOverlayModule // <----------- add this
  ],
  ...
})
export class AppModule { }
```

I will solve it for the next versions. Thanks for reporting this bug.

**Comment by zevet** [comment]
> I think this error is also shown for all components that depend on `LyOverlayModule` with lazy-loading. For now you can do is add `LyOverlayModule` in your `AppModule`.
> 
> ```ts
> ...
> import { LyOverlayModule } from '@alyle/ui';
> 
> @NgModule({
>   ...
>   imports: [
>     ...
>     LyOverlayModule // <----------- add this
>   ],
>   ...
> })
> export class AppModule { }
> ```
> 
> I will solve it for the next versions. Thanks for reporting this bug.

Thanks. I will do that
