### ISSUE TITLE
Support for Circular image cropping

### ISSUE THREAD

**Issue by cyberrspiritt** [A-l-y-l-e/Alyle-UI#90]
# :rocket: Feature request
There should be an option for us to provide the css for the cropper box. We have height, width already. can we have border-radius too?

**Comment by Enlcxx** [comment]
Yes, you can add variables to theme.

e.g.

```ts
export class GlobalVariables implements PartialThemeVariables {
  ...
  ...
  imgCropper = {
    root: {
      '& {area}, & {area}::after': {
        borderRadius: '50%'
      }
    }
  };
}
```
result:

![img](https://user-images.githubusercontent.com/8032887/60375690-81bacf00-99d8-11e9-883a-dcea8d5fc678.png)

**Comment by hammadmalick786** [comment]
@cyberrspiritt can give the implementation of this code please
