### ISSUE TITLE
Cannot find module '@alyle/ui/slider'

### ISSUE THREAD

**Issue by tiagomoucho3** [A-l-y-l-e/Alyle-UI#91]
# :beetle: Bug report

### Describe the bug
Installed the alyle version to use with Angular 7. When using the image cropper template, which uses the slider, it presents the error in app.module.ts Cannot find module '@alyle/ui/slider'

### Minimal Reproduction
Have an Angular 7 project.
Install Alyle version 2.7.8.
Use slider module.

### Exception or Error
<pre><code>
ERROR in src/app/app.module.ts(63,32): error TS2307: Cannot find module '@alyle/ui/slider'.
</code></pre>

### Which versions of Angular, Alyle UI, OS, TypeScript, browsers are affected?

**Alyle UI Version:** 
`v2.7.8`

**Angular Version:**
<pre><code>
Angular CLI: 7.3.9

Node: 10.16.0

OS: win32 x64

Angular: 7.2.15

... animations, common, compiler, compiler-cli, core, forms

... http, language-service, platform-browser

... platform-browser-dynamic, router

 

Package Version

-----------------------------------------------------------

@angular-devkit/architect 0.13.9

@angular-devkit/build-angular 0.13.9

@angular-devkit/build-optimizer 0.13.9

@angular-devkit/build-webpack 0.13.9

@angular-devkit/core 7.3.9

@angular-devkit/schematics 7.3.9

@angular/cli 7.3.9

@ngtools/webpack 7.3.9

@schematics/angular 7.3.9

@schematics/update 0.13.9

rxjs 6.5.2

typescript 3.2.4

webpack 4.29.0

</code></pre>

**Comment by Enlcxx** [comment]
Hi @tiagomoucho3, The slider is not available for Angular 7, only for Angular 8, and there is no support for Angular 7

**Comment by tiagomoucho3** [comment]
Thanks for the fast reply @Enlcxx.
Will it have support eventually or it is really just for Angular 8?

**Comment by Enlcxx** [comment]
No, there will be no support for Angular 7, the new fixes and features will only be for version 8
