### ISSUE TITLE
help : Ly-Icon cuse destroy everything

### ISSUE THREAD

**Issue by xcomhz** [A-l-y-l-e/Alyle-UI#95]
# :beetle: Bug report

### Describe the bug
when i add ly-icon to code all other components collapse and i just see a small button
i copy the various sample codes from your site but it does not work.other components is working.
Angular show this behavior when there is an undeclared import in app.module so i think the problem is a module i have to install or import!

### Exception or Error
<pre><code>

</code></pre>

### Screenshots

before using an Icon :
![image](https://user-images.githubusercontent.com/20340737/66955394-3b918600-f030-11e9-96c7-4bb380395a2a.png)
after using an Icon :
![image](https://user-images.githubusercontent.com/20340737/66955316-1866d680-f030-11e9-818b-7d0af646ab37.png)

### Which versions of Angular, Alyle UI, OS, TypeScript, browsers are affected?

**Alyle UI Version:** 
new version
**Angular Version:**
<pre><code>

Angular CLI: 8.1.2
Node: 11.14.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.801.2
@angular-devkit/core         8.1.2
@angular-devkit/schematics   8.1.2
@schematics/angular          8.1.2
@schematics/update           0.801.2
rxjs                         6.4.0
</code></pre>

**Comment by Enlcxx** [comment]
Already added `LyIconModule`?

**Comment by CarvalhoWesley** [comment]
I have the same problem too, but I include LyIconModule, but it still breaks the layout.

**Comment by Enlcxx** [comment]
Is it displays an error on the console? I think the module `HttpClientModule` is missing.

**Comment by CarvalhoWesley** [comment]
the problem was really that, now it's solved haha. Thanks.
