### ISSUE TITLE
Cannot read property 'button' of undefined in karma test

### ISSUE THREAD

**Issue by medTL** [A-l-y-l-e/Alyle-UI#96]
# :beetle: Bug report

### Describe the bug
i have a 'Cannot read property 'button' of undefined' error when testing my angular app, the components that showing this error are from lazy loaded module and i am using ly-button in html
### Screenshots

![image](https://user-images.githubusercontent.com/19789975/67093375-66ebb080-f1a9-11e9-9d03-f5d6f4030a40.png)

### Which versions of Angular, Alyle UI, OS, TypeScript, browsers are affected?

**Alyle UI Version:** 
2.7.8

**Angular Version:**
7.2.15

**Comment by Enlcxx** [comment]
In karma he did not declare the themes
