### ISSUE TITLE
The bug about ly-Icon i've reported before

### ISSUE THREAD

**Issue by xcomhz** [A-l-y-l-e/Alyle-UI#97]
# :beetle: Bug report
Hi,
as i mentioned before ly-Icon destroys everything in target page , i could enable debug in the running page and realized that it needs to import HttpClientModule in the module contained module.
xcomhz@gmail.com  
### Exception or Error
<pre><code>

</code></pre>

### Which versions of Angular, Alyle UI, OS, TypeScript, browsers are affected?

**Alyle UI Version:** 
`vx.x.x`

**Angular Version:**
<pre><code>

</code></pre>

**Comment by Enlcxx** [comment]
Does that mean it is already working?
